# Generated by Django 3.1.4 on 2020-12-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formularios',
            table='Formularios',
        ),
    ]
